variables:
  HUGO_VERSION: 0.150.1
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: alpine:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - set -eux pipefail
    - apk update && apk upgrade
    - apk add wget gcc musl-dev linux-headers make g++ clang-dev git nodejs npm rclone python3 python3-dev pango
    - python3 -m venv /tmp/tmpvenv
    - /tmp/tmpvenv/bin/pip install -r themes/ishill/requirements.txt
    - wget -O /tmp/hugo.tgz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz"
    - tar -xzf /tmp/hugo.tgz
    - npm install -g sass
    - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
    - ./hugo --gc --minify
    - source /tmp/tmpvenv/bin/activate && cd public && sh ./zineify.sh && cd ..
    - ./hugo --gc --minify --baseURL "$CI_PAGES_URL/"
    - rclone --config $RCLONE_CONFIG sync public autistici:html-ishill
    - rclone --config $RCLONE_CONFIG sync public nearlyfreespeech:/home/public
  pages:
    publish: public
  artifacts:
    paths:
      - public
    expire_in: 1 week
