variables:
  HUGO_VERSION: 0.148.1

default:
  image: ubuntu:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - set -eux pipefail
    - apt update && apt upgrade -y
    - apt install -y wget git nodejs python3-venv # https://github.com/rrthomas/psutils
    - python3 -m venv /tmp/tmpvenv
    - /tmp/tmpvenv/bin/pip install pdfimpose
    - wget -O hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
    - dpkg -i hugo.deb
    - rm hugo.deb
    - npm install -g @vivliostyle/cli # https://github.com/vivliostyle/vivliostyle-cli?tab=readme-ov-file
    - npm install -g sass
    - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
    - hugo --gc --minify --baseURL "$CI_PAGES_URL/"
    - cd public && source /tmp/tmpvenv/bin/activate && bash ./zineify.sh
  pages:
    publish: public
  artifacts:
    paths:
      - public
    expire_in: 1 week
