variables:
  HUGO_VERSION: 0.150.1
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: ubuntu:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - set -eux pipefail
    - apt update && apt upgrade -y
    - apt install -y wget git nodejs npm python3-venv libpango-1.0-0 libpangoft2-1.0-0
    - python3 -m venv /tmp/tmpvenv
    - /tmp/tmpvenv/bin/pip install -r themes/ishill/requirements.txt
    - wget -O hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
    - dpkg -i hugo.deb
    - rm hugo.deb
    - npm install -g sass
    - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
    - hugo --gc --minify
    - source /tmp/tmpvenv/bin/activate && cd public && bash ./zineify.sh
    - hugo --gc --minify --baseURL "$CI_PAGES_URL/"
  pages:
    publish: public
  artifacts:
    paths:
      - public
    expire_in: 1 week
